<?php
$prime_alerts_default_option = [
	'enabled' => 'Y',
	'policy_enabled' => 'Y',
	'policy_register' => 'Y',
	'policy_order' => 'Y',
	'notice_everywhere' => 'N',
	'support_email' => 'info@vrn-ehk.ru',
	'support_phone' => '8-800-755-07-76',
	'extra_domains' => '',
	'notice_title_signup' => '',
	'notice_text_signup' => '',
	'notice_title_checkout' => '',
	'notice_text_checkout' => '',
	'error_text_signup' => '',
	'error_text_checkout' => '',
	'profile_banner' => 'Y',
	'profile_banner_title' => '',
	'profile_banner_text' => '',
	'color_scheme' => 'shop',
];
