CREATE TABLE IF NOT EXISTS `am_smtp_accounts` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `DOMAIN_ID` int(11) NOT NULL,
  `ACTIVE` char(1) NOT NULL DEFAULT 'Y',
  `IS_DEFAULT_DOMAIN` char(1) NOT NULL DEFAULT 'N',
  `IS_DEFAULT` char(1) NOT NULL DEFAULT 'N',
  `SMTP_HOST` varchar(255) NOT NULL,
  `SMTP_PORT` int(11) NOT NULL DEFAULT '25',
  `SECURE_TYPE` char(1) NOT NULL DEFAULT 'N',
  `EMAIL` varchar(255) NOT NULL,
  `SENDER_NAME` varchar(255) DEFAULT NULL,
  `ACCOUNT_LOGIN` varchar(255) DEFAULT NULL,
  `ACCOUNT_PASSWORD` varchar(255) DEFAULT NULL,
  `IS_IMPORT` char(1) NOT NULL DEFAULT 'N',
  `LIMIT_MINUTE` INT NULL,
  `LIMIT_HOUR` INT NULL,
  `LIMIT_DAY` INT NULL,
  `LIMIT_DOMAN_IGNORE` CHAR(1) NOT NULL DEFAULT 'N',
  PRIMARY KEY (`ID`),
  KEY `am_smtp_accounts_DOMAIN_ID_index` (`DOMAIN_ID`)
) COMMENT='Ammina SMTP: Accounts';

CREATE TABLE IF NOT EXISTS `am_smtp_domains` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `DOMAIN` varchar(255) NOT NULL,
  `DKIM_PRIVATE` text COLLATE utf8_unicode_ci,
  `DKIM_PUBLIC` text COLLATE utf8_unicode_ci,
  `DKIM_SELECTOR` varchar(255) DEFAULT NULL,
  `DKIM_PASSPHRASE` varchar(255) DEFAULT NULL,
  `LIMIT_MINUTE` INT NULL,
  `LIMIT_HOUR` INT NULL,
  `LIMIT_DAY` INT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `amsm_domains_DOMAIN_uindex` (`DOMAIN`)
) COMMENT='Ammins.smtp: Domains';

CREATE TABLE IF NOT EXISTS `am_smtp_queue` (
    `ID` int(11) NOT NULL AUTO_INCREMENT,
    `ACCOUNT_ID` int(11) NOT NULL,
    `STATUS` char(1) NOT NULL DEFAULT 'N',
    `DATE_INSERT` datetime NOT NULL,
    `DATE_SEND` datetime DEFAULT NULL,
    `FIELD_TO` VARCHAR(255) NULL DEFAULT NULL,
    `FIELD_SUBJECT` VARCHAR(511) NULL DEFAULT NULL,
    `MAIL_DATA` longtext NOT NULL,
    `LOG_DATA` longtext DEFAULT NULL,
    PRIMARY KEY (`ID`),
    KEY `IX_ACCOUNT_ID` (`ACCOUNT_ID`),
    KEY `IX_DATE_SEND` (`DATE_SEND`),
    KEY `IX_STATUS` (`STATUS`)
);

CREATE TABLE IF NOT EXISTS `am_smtp_stat_domains` (
    `ID` int(11) NOT NULL AUTO_INCREMENT,
    `DOMAIN_ID` int(11) NOT NULL,
    `SEND_DATE` date NOT NULL,
    `HOUR` int(11) DEFAULT NULL,
    `MINUTE` int(11) DEFAULT NULL,
    `CNT_SEND` INT NOT NULL DEFAULT '0',
    `CNT_ERROR` INT NOT NULL DEFAULT '0',
    PRIMARY KEY (`ID`),
    KEY `IX_DOMAIN_DATE` (`DOMAIN_ID`,`SEND_DATE`) USING BTREE
);

CREATE TABLE IF NOT EXISTS `am_smtp_stat_accounts` (
    `ID` int(11) NOT NULL AUTO_INCREMENT,
    `ACCOUNT_ID` int(11) NOT NULL,
    `SEND_DATE` date NOT NULL,
    `HOUR` int(11) DEFAULT NULL,
    `MINUTE` int(11) DEFAULT NULL,
    `CNT_SEND` INT NOT NULL DEFAULT '0',
    `CNT_ERROR` INT NOT NULL DEFAULT '0',
    PRIMARY KEY (`ID`),
    KEY `IX_ACCOUNT_DATE` (`ACCOUNT_ID`,`SEND_DATE`) USING BTREE
);