CREATE TABLE IF NOT EXISTS `am_smtp_queue` (
    `ID` int(11) NOT NULL AUTO_INCREMENT,
    `ACCOUNT_ID` int(11) NOT NULL,
    `STATUS` char(1) NOT NULL DEFAULT 'N',
    `DATE_INSERT` datetime NOT NULL,
    `DATE_SEND` datetime DEFAULT NULL,
    `MAIL_DATA` longtext NOT NULL,
    `LOG_DATA` longtext DEFAULT NULL,
    PRIMARY KEY (`ID`),
    KEY `IX_ACCOUNT_ID` (`ACCOUNT_ID`),
    KEY `IX_DATE_SEND` (`DATE_SEND`),
    KEY `IX_STATUS` (`STATUS`)
);

ALTER TABLE `am_smtp_domains` ADD `LIMIT_MINUTE` INT NULL AFTER `DKIM_PASSPHRASE`, ADD `LIMIT_HOUR` INT NULL AFTER `LIMIT_MINUTE`, ADD `LIMIT_DAY` INT NULL AFTER `LIMIT_HOUR`;

ALTER TABLE `am_smtp_accounts` ADD `LIMIT_MINUTE` INT NULL AFTER `IS_IMPORT`, ADD `LIMIT_HOUR` INT NULL AFTER `LIMIT_MINUTE`, ADD `LIMIT_DAY` INT NULL AFTER `LIMIT_HOUR`,  ADD `LIMIT_DOMAN_IGNORE` CHAR(1) NOT NULL DEFAULT 'N' AFTER `LIMIT_DAY`;

CREATE TABLE IF NOT EXISTS `am_smtp_stat_domains` (
    `ID` int(11) NOT NULL AUTO_INCREMENT,
    `DOMAIN_ID` int(11) NOT NULL,
    `SEND_DATE` date NOT NULL,
    `HOUR` int(11) DEFAULT NULL,
    `MINUTE` int(11) DEFAULT NULL,
    `CNT_SEND` INT NOT NULL DEFAULT '0',
    `CNT_ERROR` INT NOT NULL DEFAULT '0',
    PRIMARY KEY (`ID`),
    KEY `IX_DOMAIN_DATE` (`DOMAIN_ID`,`SEND_DATE`) USING BTREE
);

CREATE TABLE IF NOT EXISTS `am_smtp_stat_accounts` (
    `ID` int(11) NOT NULL AUTO_INCREMENT,
    `ACCOUNT_ID` int(11) NOT NULL,
    `SEND_DATE` date NOT NULL,
    `HOUR` int(11) DEFAULT NULL,
    `MINUTE` int(11) DEFAULT NULL,
    `CNT_SEND` INT NOT NULL DEFAULT '0',
    `CNT_ERROR` INT NOT NULL DEFAULT '0',
    PRIMARY KEY (`ID`),
    KEY `IX_ACCOUNT_DATE` (`ACCOUNT_ID`,`SEND_DATE`) USING BTREE
);